
language: node_js
node_js:
  - stable
  - lts/carbon
  - lts/dubnium
env:
  matrix:
  global:
branches:
  only:
    - master
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn ci
after_script:
- npx codecov
notifications:
  email: false
